name: toggle_list
description: An easy-to-use and highly customizable expandable list widget for your Flutter application.
version: 0.2.0
homepage: https://binarybush.dev/
repository: https://github.com/binarybush/toggle_list 
issue_tracker: https://github.com/binarybush/toggle_list/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
